/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(stack)'}/create-exam` | `/create-exam`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/question-bank` | `/question-bank`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SortRow`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SortDropdown`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/exam-detail` | `/exam-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/question-form` | `/question-form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/team` | `/team`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(stack)'}/create-exam` | `/create-exam`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/question-bank` | `/question-bank`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SortRow`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SortDropdown`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/exam-detail` | `/exam-detail`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/question-form` | `/question-form`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(stack)'}/team` | `/team`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(stack)'}/create-exam${`?${string}` | `#${string}` | ''}` | `/create-exam${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/question-bank${`?${string}` | `#${string}` | ''}` | `/question-bank${`?${string}` | `#${string}` | ''}` | `/../components/SortRow${`?${string}` | `#${string}` | ''}` | `/../components/SortDropdown${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/exam-detail${`?${string}` | `#${string}` | ''}` | `/exam-detail${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/question-form${`?${string}` | `#${string}` | ''}` | `/question-form${`?${string}` | `#${string}` | ''}` | `${'/(stack)'}/team${`?${string}` | `#${string}` | ''}` | `/team${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exams${`?${string}` | `#${string}` | ''}` | `/exams${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/guide${`?${string}` | `#${string}` | ''}` | `/guide${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(stack)'}/create-exam` | `/create-exam`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/question-bank` | `/question-bank`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SortRow`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SortDropdown`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/exam-detail` | `/exam-detail`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/question-form` | `/question-form`; params?: Router.UnknownInputParams; } | { pathname: `${'/(stack)'}/team` | `/team`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exams` | `/exams`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/guide` | `/guide`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stats` | `/stats`; params?: Router.UnknownInputParams; };
    }
  }
}
